services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      # Red interna aislada para evitar problemas con las bases de datos
      - internal_network
      - traefik
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  odoo:
    container_name: ${COMPOSE_PROJECT_NAME}_odoo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ODOO_VERSION: ${ODOO_VERSION}
        ODOO_REQUIREMENTS: ${ODOO_REQUIREMENTS}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_odoo.rule=Host(`${DNS}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_odoo.entrypoints=websecure
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}_odoo.tls.certresolver=myresolver
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_odoo.loadbalancer.server.port=${ODOO_INTERNAL_PORT}
      # Especificar la red para traefik
      - traefik.docker.network=traefik
    ports:
      - "${ODOO_EXPOSED_PORT}:${ODOO_INTERNAL_PORT}"
    volumes:
      - ${ODOO_CONFIG}:/etc/odoo
      - ${ODOO_ADDONS}:/mnt/extra-addons
      - ${ODOO_LOG}:/var/log/odoo
      - odoo_data:/var/lib/odoo
    environment:
      # Usar el nombre específico del contenedor de DB
      - HOST=${COMPOSE_PROJECT_NAME}_db
      - USER=odoo
      - PASSWORD=odoo
      - DB_MAXCONN=64
      - DB_TEMPLATE=template0
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal_network  # Red interna aislada
      - traefik          # Red externa para traefik
    restart: unless-stopped

volumes:
  odoo_data:
    name: ${COMPOSE_PROJECT_NAME}_odoo_data
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data

networks:
  # Red interna solo para este proyecto
  internal_network:
    name: ${COMPOSE_PROJECT_NAME}_internal
    driver: bridge
  # Red externa existente para traefik
  traefik:
    external: true