version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

  odoo:
    build:
      context: ./odoo
      dockerfile: Dockerfile
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - ./odoo/log:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    entrypoint: ["/wait-for-db.sh"]
    command: [
      "odoo",
      "--db_host=db",
      "--db_port=5432",
      "--db_user=odoo",
      "--db_password=odoo"
    ]
    restart: always

volumes:
  odoo-web-data:
    name: odoo-18-docker_odoo-web-data
  odoo-db-data:
    name: odoo-18-docker_odoo-db-data
