- name: Docker Management Playbook
  hosts: servers
  gather_facts: yes
  tasks:
    - name: Ensure Docker is installed
      yum:
        name: docker
        state: present
      vars:
        ansible_python_interpreter: /usr/bin/python2
    - name: Start Docker service
      service:
        name: docker
        state: started