services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      # Internal network
      - internal_network
      # External traefik network
      - traefik
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U odoo -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  odoo:
    container_name: ${COMPOSE_PROJECT_NAME}_odoo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ODOO_VERSION: ${ODOO_VERSION}
        ODOO_REQUIREMENTS: ${ODOO_REQUIREMENTS}
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.services.${COMPOSE_PROJECT_NAME}_odoo.loadbalancer.server.port=${ODOO_INTERNAL_PORT}


    ports:
      - "${ODOO_EXPOSED_PORT}:${ODOO_INTERNAL_PORT}"
    volumes:
      - ${ODOO_CONFIG}:/etc/odoo
      - ${ODOO_ADDONS}:/mnt/extra-addons
      - ${ODOO_LOG}:/var/log/odoo
      - odoo_data:/var/lib/odoo
    environment:
      # Postgres container name
      - HOST=${COMPOSE_PROJECT_NAME}_db
      # Postgres user
      - USER=odoo
      # Postgres password
      - PASSWORD=odoo
      - DB_TEMPLATE=template0
    depends_on:
      db:
        condition: service_healthy
    networks:
      # Internal network for containers
      - internal_network
      # External traefik network
      - traefik
    restart: unless-stopped

volumes:
  odoo_data:
    name: ${COMPOSE_PROJECT_NAME}_odoo_data
  db_data:
    name: ${COMPOSE_PROJECT_NAME}_db_data

networks:
  # Internal name with custom name for this environment
  internal_network:
    name: ${COMPOSE_PROJECT_NAME}_internal
    driver: bridge
  # Existing external traefik network
  traefik:
    external: true