services:
  https-portal:
    image: steveltn/https-portal:latest
    ports:
      - '80:80'
      - '443:443'
    restart: always
    depends_on:
      - web
    environment:
      DOMAINS: 'zoltar238.odoo.com -> http://web:8069'
      STAGE: 'staging'
      # FORCE_RENEW: 'true'
    volumes:
      - https-portal-data:/var/lib/https-portal

volumes:
  https-portal-data:
