version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5433:5432'
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d odoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:18.0
    container_name: odoo
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
    # Enable to see live logs instead of log file
    tty: true
    volumes:
      - ./odoo/addons:/mnt/extra-addons
      - ./odoo/config:/etc/odoo
      - ./odoo/log:/var/log/odoo/
      - odoo-web-data:/var/lib/odoo
    environment:
      - HOST=db
      - DATABASE=odoo
      - USER=odoo
      - PASSWORD=odoo
      - ADMIN_PASSWORD=odoo
    # Use root user
    user: root
    command: >
      bash -c "
      until pg_isready -h db -p 5432 -U odoo; do
        echo 'Waiting for PostgreSQL to be ready...';
        sleep 2;
      done
      && pip install python-barcode --break-system-packages
      && exec odoo --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo
      "
    restart: always

volumes:
  odoo-web-data:
    name: odoo-18-docker_odoo-web-data
  odoo-db-data:
    name: odoo-18-docker_odoo-db-data